service: ton-panel
provider:
  name: aws
  runtime: nodejs14.x
  stage: api
  region: sa-east-1
  memorySize: 256
functions:
  app:
    handler: app/app.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true